In [10]:
import numpy as np
import pandas as pd
import os

In [11]:
players_df = pd.read_csv(".././Data/player_info_merged_normalized.csv")

In [12]:
players_df.head(60)

Players               Teams  Goals scored  Total shots  \
0          Buffon\n (GK)            Juventus          0.00     0.000000   
1                  Pogba            Juventus          0.00     0.142857   
2              Marchisio            Juventus          0.00     0.214286   
3                 Morata            Juventus          0.25     0.214286   
4                  Tévez            Juventus          0.00     0.285714   
5               Barzagli            Juventus          0.00     0.000000   
6                Bonucci            Juventus          0.00     0.000000   
7                  Pirlo            Juventus          0.00     0.000000   
8                  Vidal            Juventus          0.00     0.142857   
9           Lichtsteiner            Juventus          0.00     0.000000   
10                  Evra            Juventus          0.00     0.000000   
11        Storari\n (GK)            Juventus          0.00     0.000000   
12               Ogbonna            Juventus          0.00     0.000000   
13                 Coman            Juventus          0.00     0.000000   
14              Llorente            Juventus          0.00     0.000000   
15                Padoin            Juventus          0.00     0.000000   
16               Sturaro            Juventus          0.00     0.000000   
17               Pereyra            Juventus          0.00     0.000000   
18  Massimiliano Allegri     Juventus(COACH)          0.00     0.000000   
19     Ter Stegen\n (GK)           Barcelona          0.00     0.000000   
20                 Piqué           Barcelona          0.00     0.071429   
21               Rakitić           Barcelona          0.25     0.071429   
22       Sergio Busquets           Barcelona          0.00     0.000000   
23               Iniesta           Barcelona          0.00     0.000000   
24           Luis Suárez           Barcelona          0.25     0.500000   
25                 Messi           Barcelona          0.00     0.214286   
26                Neymar           Barcelona          0.25     0.214286   
27            Mascherano           Barcelona          0.00     0.000000   
28            Jordi Alba           Barcelona          0.00     0.071429   
29            Dani Alves           Barcelona          0.00     0.071429   
30          Bravo\n (GK)           Barcelona          0.00     0.000000   
31        Xavi Hernández           Barcelona          0.00     0.000000   
32       Pedro Rodríguez           Barcelona          0.00     0.000000   
33               Rafinha           Barcelona          0.00     0.000000   
34                Bartra           Barcelona          0.00     0.000000   
35               Adriano           Barcelona          0.00     0.000000   
36               Mathieu           Barcelona          0.00     0.000000   
37          Luis Enrique    Barcelona(COACH)          0.00     0.000000   
38       Casillas\n (GK)         Real Madrid          0.00     0.000000   
39                Varane         Real Madrid          0.00     0.000000   
40                 Ramos         Real Madrid          0.00     0.142857   
41               Ronaldo         Real Madrid          0.25     0.214286   
42                 Kroos         Real Madrid          0.00     0.214286   
43               Benzema         Real Madrid          0.00     0.285714   
44       James Rodríguez         Real Madrid          0.00     0.071429   
45                  Bale         Real Madrid          0.00     0.500000   
46               Marcelo         Real Madrid          0.00     0.071429   
47              Carvajal         Real Madrid          0.00     0.000000   
48                  Isco         Real Madrid          0.00     0.071429   
49          Navas\n (GK)         Real Madrid          0.00     0.000000   
50                  Pepe         Real Madrid          0.00     0.000000   
51        Fábio Coentrão         Real Madrid          0.00     0.000000   
52             Hernández         Real Madr

In [104]:
players_df.shape

(5652, 12)

In [8]:
players_df[players_df.isna().any(axis=1)]

Empty DataFrame
Columns: [Players, Teams, Goals scored, Total shots, Shots on Target, Assists, Interceptions, Crosses, Fouls committed, Offsides, Time Played, Home_Game]
Index: []

In [13]:
idx = []
for i in range(players_df.shape[0]):
    if "COACH" in players_df.iloc[i,1]:
        idx.append(i)
print(idx)
players_df = players_df.drop(idx)


[18, 37, 56, 75, 94, 113, 132, 151, 170, 189, 208, 227, 246, 265, 284, 303, 322, 341, 360, 379, 398, 417, 436, 455, 474, 493, 512, 531, 550, 569, 588, 607, 626, 645, 664, 683, 702, 721, 740, 759, 778, 797, 816, 835, 854, 873, 892, 911, 930, 949, 968, 987, 1006, 1025, 1044, 1063, 1082, 1101, 1120, 1139, 1158, 1177, 1196, 1215, 1234, 1253, 1272, 1291, 1310, 1329, 1348, 1367, 1386, 1405, 1424, 1443, 1462, 1481, 1500, 1519, 1538, 1557, 1576, 1595, 1614, 1633, 1652, 1671, 1690, 1709, 1728, 1747, 1766, 1785, 1804, 1823, 1842, 1861, 1880, 1899, 1918, 1937, 1956, 1975, 1994, 2013, 2032, 2051, 2070, 2089, 2108, 2127, 2146, 2165, 2184, 2203, 2222, 2241, 2260, 2279, 2298, 2317, 2336, 2355, 2374, 2393, 2412, 2431, 2450, 2469, 2488, 2507, 2526, 2545, 2564, 2583, 2602, 2621, 2639, 2658, 2677, 2696, 2715, 2734, 2753, 2772, 2791, 2810, 2829, 2848, 2867, 2886, 2905, 2924, 2942, 2961, 2980, 2999, 3018, 3037, 3056, 3075, 3094, 3113, 3132, 3151, 3170, 3189, 3208, 3227, 3246, 3265, 3284, 3303, 3322, 3341, 

In [14]:
for i in range(1,players_df.shape[0]-1):
    if players_df.iloc[i-1,1] == players_df.iloc[i+1,1] and players_df.iloc[i-1,1] != players_df.iloc[i,1]:
        players_df.iloc[i,1] = players_df.iloc[i-1,1]

In [15]:
players_df.reset_index(drop=True,inplace = True)

In [16]:
drop_idxs = [4185, 4186, 4189, 4193, 4196
#              , 4209, 4213, 4214, 4125, 4218
            ]
players_df = players_df.drop(drop_idxs)
players_df.reset_index(drop=True,inplace = True)

In [17]:
drop_idxs = [4203, 4204, 4208, 4209, 4213
#              , 4209, 4213, 4214, 4125, 4218
            ]
players_df = players_df.drop(drop_idxs)
players_df.reset_index(drop=True,inplace = True)

In [18]:
line = pd.DataFrame({"Players": "Filler", "Teams": "Dortmund", "Goals scored": 0.0, "Total shots": 0.0,
                 "Shots on Target": 0.0, "Assists": 0.0, "Interceptions": 0.0, "Crosses": 0.0, "Fouls committed": 0.0,
                 "Offsides": 0.0, "Time Played": 0.0}, index=[2500.5])
players_df = players_df.append(line, ignore_index=False)
players_df = players_df.sort_index().reset_index(drop=True)

line = pd.DataFrame({"Players": "Filler", "Teams": "Arsenal", "Goals scored": 0.0, "Total shots": 0.0,
                 "Shots on Target": 0.0, "Assists": 0.0, "Interceptions": 0.0, "Crosses": 0.0, "Fouls committed": 0.0,
                 "Offsides": 0.0, "Time Played": 0.0}, index=[2788.5])
players_df = players_df.append(line, ignore_index=False)
players_df = players_df.sort_index().reset_index(drop=True)

In [19]:
last_team = 'Juventus'
team_idx = 0
cnt = 0
team_players_dict = {}
for i in range(players_df.shape[0]):
    if "(GK)" in players_df.iloc[i,0] and players_df.iloc[i,1] != last_team: 
        team_players_dict[team_idx] = cnt
        if cnt == 36:
            print(i,players_df.iloc[i,1],team_idx)
        cnt = 1
        team_idx += 1 
    else:
        cnt += 1
    last_team = players_df.iloc[i,1]
    

126 Bayern 5
198 Atlético 8
342 Bayern 15
1170 Bayern 60
1386 Man. City 71
1926 Barcelona 100
2214 Juventus 115
2430 Real Madrid 126
3258 Real Madrid 171
3474 Man. City 182
4194 Liverpool 221
4302 Liverpool 226
4518 Barcelona 237


In [20]:
team_players_dict

{0: 18,
 1: 18,
 2: 18,
 3: 18,
 4: 18,
 5: 36,
 6: 18,
 7: 18,
 8: 36,
 9: 18,
 10: 18,
 11: 18,
 12: 18,
 13: 18,
 14: 18,
 15: 36,
 16: 18,
 17: 18,
 18: 18,
 19: 18,
 20: 18,
 21: 18,
 22: 18,
 23: 18,
 24: 18,
 25: 18,
 26: 18,
 27: 18,
 28: 18,
 29: 18,
 30: 18,
 31: 18,
 32: 18,
 33: 18,
 34: 18,
 35: 18,
 36: 18,
 37: 18,
 38: 18,
 39: 18,
 40: 18,
 41: 18,
 42: 18,
 43: 18,
 44: 18,
 45: 18,
 46: 18,
 47: 18,
 48: 18,
 49: 18,
 50: 18,
 51: 18,
 52: 18,
 53: 18,
 54: 18,
 55: 18,
 56: 18,
 57: 18,
 58: 18,
 59: 18,
 60: 36,
 61: 18,
 62: 18,
 63: 18,
 64: 18,
 65: 18,
 66: 18,
 67: 18,
 68: 18,
 69: 18,
 70: 18,
 71: 36,
 72: 18,
 73: 18,
 74: 18,
 75: 18,
 76: 18,
 77: 18,
 78: 18,
 79: 18,
 80: 18,
 81: 18,
 82: 18,
 83: 18,
 84: 18,
 85: 18,
 86: 18,
 87: 18,
 88: 18,
 89: 18,
 90: 18,
 91: 18,
 92: 18,
 93: 18,
 94: 18,
 95: 18,
 96: 18,
 97: 18,
 98: 18,
 99: 18,
 100: 36,
 101: 18,
 102: 18,
 103: 18,
 104: 18,
 105: 18,
 106: 18,
 107: 18,
 108: 18,
 109: 18,
 110: 18,


In [21]:
players_df.shape

(5652, 12)

In [ ]:
2501
2789

In [81]:
players_df.at[2501,'Home_Game'] = 1
players_df.at[2789,'Home_Game'] = 1

In [82]:
players_df.iloc[2501,:]

Players              Filler
Teams              Dortmund
Goals scored              0
Total shots               0
Shots on Target           0
Assists                   0
Interceptions             0
Crosses                   0
Fouls committed           0
Offsides                  0
Time Played               0
Home_Game                 1
Name: 2501, dtype: object

In [83]:
players_df[players_df['Home_Game'].isnull()]

Empty DataFrame
Columns: [Players, Teams, Goals scored, Total shots, Shots on Target, Assists, Interceptions, Crosses, Fouls committed, Offsides, Time Played, Home_Game]
Index: []

In [84]:
player_dict_flag = {}
player_dict_idx = {}
player_dict_data = {}

for i in range(players_df.shape[0]):
    player_name = players_df.iloc[i,0]
    player_dict_idx[player_name] = []
    player_dict_flag[player_name] = 0
    
for i in range(players_df.shape[0]):
    player_name = players_df.iloc[i,0]
    if player_dict_flag[player_name] == 1:
        temp = []
        for j in range(i):
            if players_df.iloc[j,0] == player_name:
                temp.append(players_df.iloc[j,2:-1].values)
        list_avg = np.sum(temp,axis = 0) / len(temp)
        if player_name == "Vidal":
            print(list_avg)
            print("added here")
        list_avg2 = np.append(list_avg,players_df.iloc[i,-1])
        player_dict_data[i] = list_avg2
        
    else:
        player_dict_data[i] = players_df.iloc[i,2:].values
        if player_name == "Vidal":
            print("lol here")
    player_dict_idx[player_name].append(i)
    player_dict_flag[player_name] = 1
    

lol here
[0.0 0.14285714285714302 0.0 0.0 0.272727272727273 0.0 0.7142857142857142
 0.0 0.68695652173913]
added here
[0.0 0.14285714285714302 0.125 0.0 0.1363636363636365 0.08
 0.5714285714285716 0.07142857142857151 0.734782608695652]
added here
[0.0 0.09523809523809534 0.08333333333333333 0.0 0.181818181818182
 0.05333333333333334 0.5238095238095241 0.09523809523809534
 0.7507246376811594]
added here
[0.0 0.07142857142857151 0.0625 0.0 0.181818181818182 0.04
 0.5000000000000002 0.07142857142857151 0.7304347826086955]
added here
[0.05 0.12857142857142861 0.15 0.0 0.181818181818182 0.04
 0.5142857142857145 0.057142857142857204 0.7408695652173913]
added here
[0.041666666666666664 0.11904761904761918 0.125 0.0 0.19696969696969716
 0.03333333333333333 0.5476190476190478 0.04761904761904767
 0.7478260869565218]
added here
[0.03571428571428571 0.10204081632653073 0.10714285714285714 0.0
 0.168831168831169 0.03428571428571429 0.4897959183673471
 0.061224489795918435 0.7478260869565218]
added 

In [85]:
player_dict_idx

{'Buffon\n (GK)': [0,
  54,
  144,
  234,
  396,
  486,
  828,
  1566,
  1872,
  2088,
  2160,
  2214,
  2322,
  2520,
  2628,
  2862,
  3366,
  3528,
  3798,
  4140,
  4788,
  5202],
 'Pogba': [1, 56, 488, 830, 1569, 1875, 3685, 3955, 4485, 4502, 5187],
 'Marchisio': [2,
  57,
  146,
  236,
  398,
  489,
  831,
  1874,
  2102,
  2174,
  2217,
  2532,
  2632,
  2875,
  3379,
  3541,
  3810,
  4152],
 'Morata': [3,
  58,
  147,
  237,
  399,
  490,
  832,
  1568,
  1885,
  2122,
  2159,
  2249,
  2392,
  2445,
  2841,
  3040,
  3630,
  4009,
  4743,
  4949,
  5224,
  5611],
 'Tévez': [4, 59, 148, 238, 400, 491, 833],
 'Barzagli': [5,
  68,
  158,
  239,
  410,
  501,
  1572,
  1876,
  2094,
  2166,
  2220,
  2335,
  2533,
  2642,
  2869,
  3536,
  3808,
  4441],
 'Bonucci': [6,
  60,
  149,
  240,
  401,
  492,
  834,
  1574,
  1879,
  2096,
  2168,
  2222,
  2330,
  2528,
  2636,
  4435,
  4560,
  4722,
  4959,
  5462],
 'Pirlo': [7, 61, 150, 241, 402, 835],
 'Vidal': [8,
  62,
  151,


In [88]:
player_dict_data

{0: array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7826086956521741, 0.0],
       dtype=object),
 1: array([0.0, 0.14285714285714302, 0.25, 0.0, 0.0, 0.0, 0.28571428571428603,
        0.0, 0.7826086956521741, 0.0], dtype=object),
 2: array([0.0, 0.214285714285714, 0.5, 0.0, 0.18181818181818202, 0.0, 0.0,
        0.0, 0.7826086956521741, 0.0], dtype=object),
 3: array([0.25, 0.214285714285714, 0.25, 0.0, 0.09090909090909101, 0.0, 0.0,
        0.0, 0.7391304347826091, 0.0], dtype=object),
 4: array([0.0, 0.28571428571428603, 0.5, 0.33333333333333304, 0.0, 0.04,
        0.28571428571428603, 0.0, 0.7826086956521741, 0.0], dtype=object),
 5: array([0.0, 0.0, 0.0, 0.0, 0.272727272727273, 0.0, 0.14285714285714302,
        0.0, 0.7826086956521741, 0.0], dtype=object),
 6: array([0.0, 0.0, 0.0, 0.0, 0.09090909090909101, 0.0, 0.5714285714285711,
        0.0, 0.7826086956521741, 0.0], dtype=object),
 7: array([0.0, 0.0, 0.0, 0.0, 0.09090909090909101, 0.36, 0.0, 0.0,
        0.7826086956521741, 

In [89]:
len(player_dict_data)

5652

In [90]:
for key,value in player_dict_data.items():
    print(player_dict_data[key].shape)

(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,

(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,)
(10,

In [91]:
X = []
for i in range(0,len(player_dict_data),36):
    temp = []
    for j in range(36):
        temp.append(player_dict_data[i+j])
        if j == 17 and len(X) == 77:
            print(i+j)
            print(player_dict_data[i+j])
    X.append(temp)

2789
[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0]


In [92]:
X_input = np.asarray(X)
X_input.shape

(157, 36, 10)

In [93]:
X_input[77][17]

array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0], dtype=object)

In [94]:
with open('players_X_final.npy', 'wb') as f:
    np.save(f, X_input)

In [95]:
distilled_rows = []
for i in range(0,players_df.shape[0],36):
    temp = []
    for j in range(36):
        temp.append(players_df.loc[i+j,['Goals scored']].values[0])
        temp.append(players_df.loc[i+j,['Assists']].values[0])
        temp.append(players_df.loc[i+j,['Fouls committed']].values[0])
        temp.append(players_df.loc[i+j,['Total shots']].values[0])
        temp.append(players_df.loc[i+j,['Shots on Target']].values[0])
        temp.append(players_df.loc[i+j,['Interceptions']].values[0])
        temp.append(players_df.loc[i+j,['Crosses']].values[0])
        temp.append(players_df.loc[i+j,['Time Played']].values[0])
#         temp.append(players_df.loc[i+j,['Goals scored','Assists','Fouls committed','Total shots','Shots on Target','Interceptions','Fouls committed','Time Played']].values.reshape((8,1)))
    distilled_rows.append(temp)

In [97]:
matches_df = pd.read_csv(".././Data/match_info_merged_normalized.csv")

In [98]:
blocks = matches_df['Blocks'].values
possession = matches_df['Possession'].values
total_passes = matches_df['Passes'].values
passing_accuracy = matches_df['Passing Accuracy'].values
corners = matches_df['Corners'].values

blocks_1 = []
blocks_2 = []
possession_1 = []
total_passes_1 = []
total_passes_2 = []
passing_accuracy_1 = []
passing_accuracy_2 = []
corners_1 = []
corners_2 = []

for i in range(0,len(blocks),2):
    blocks_1.append(blocks[i])
    
for i in range(1,len(blocks),2):
    blocks_2.append(blocks[i])
    
for i in range(0,len(possession),2):
    possession_1.append(possession[i])
    
for i in range(0,len(total_passes),2):
    total_passes_1.append(total_passes[i])
    
for i in range(1,len(total_passes),2):
    total_passes_2.append(total_passes[i])
    
for i in range(0,len(passing_accuracy),2):
    passing_accuracy_1.append(passing_accuracy[i])
    
for i in range(1,len(passing_accuracy),2):
    passing_accuracy_2.append(passing_accuracy[i])
    
for i in range(0,len(corners),2):
    corners_1.append(corners[i])
    
for i in range(1,len(corners),2):
    corners_2.append(corners[i])
    
match_features = []
for i in range(len(corners_1)):
    match_features.append([blocks_1[i],blocks_2[i],possession[i],total_passes_1[i],total_passes_2[i],passing_accuracy_1[i],passing_accuracy_2[i],corners_1[i],corners_2[i]])


In [99]:
output = []
for i in range(len(match_features)):
    output.append(match_features[i] + distilled_rows[i])

In [100]:
Y = np.asarray(output)
Y.shape

(157, 297)

In [101]:
with open('Y_final.npy', 'wb') as f:
    np.save(f, Y)

In [102]:
# remaining matches;
# Juventus(H) vs Lyon
# Manchester City(H) vs Real madrid
# Bayern(H) vs Chelsea
# Barcelona(H) vs Napoli

In [105]:
import pickle
with open('teams_last_embedding.p', 'rb') as fp:
    data = pickle.load(fp)

In [106]:
data.keys()

dict_keys(['Juventus', 'Barcelona', 'Real Madrid', 'Bayern', 'Atlético', 'Monaco', 'Paris', 'Porto', 'Dortmund', 'Man. City', 'Leverkusen', 'Arsenal', 'Shakhtar Donetsk', 'Chelsea', 'Schalke', 'Basel', 'Benfica', 'Wolfsburg', 'PSV', 'Dynamo Kyiv', 'Zenit', 'Roma', 'Gent', 'Leicester', 'Sevilla', 'Napoli', 'Liverpool', 'Beşiktaş', 'Man. United', 'Tottenham', 'Ajax', 'Lyon', 'Atalanta', 'Valencia', 'Leipzig'])

In [107]:
last_team_squads = {}
for elem in data.keys():
    last_team_squads[elem] = players_df[players_df['Teams'] == elem]['Players'][-18:].values

In [108]:
last_team_squads['Juventus']

array(['Szczęsny\n\n (GK)', 'De Ligt', 'Pjanić', 'Ronaldo', 'Dybala',
       'Alex Sandro', 'Danilo', 'Cuadrado', 'Bonucci', 'Rabiot',
       'Bentancur', 'Buffon\n\n (GK)', 'De Sciglio', 'Ramsey', 'Matuidi',
       'Higuaín', 'Rugani', 'Bernardeschi'], dtype=object)

In [109]:
players_df[players_df['Teams'] == 'Juventus']['Players'][-18:].values

array(['Szczęsny\n\n (GK)', 'De Ligt', 'Pjanić', 'Ronaldo', 'Dybala',
       'Alex Sandro', 'Danilo', 'Cuadrado', 'Bonucci', 'Rabiot',
       'Bentancur', 'Buffon\n\n (GK)', 'De Sciglio', 'Ramsey', 'Matuidi',
       'Higuaín', 'Rugani', 'Bernardeschi'], dtype=object)

In [110]:
last_embedding_players = {}

for elem in last_team_squads.keys():
    team_squad = last_team_squads[elem]
    team_embedding = []
    for player in team_squad:
        last_idx = player_dict_idx[player][-1]
        team_embedding.append(player_dict_data[last_idx])
    last_embedding_players[elem] = team_embedding


In [111]:
try:
import cPickle as pickle
except ImportError:  # python 3.x
import pickle

with open('players_last_embedding.p', 'wb') as fp:
pickle.dump(last_embedding_players, fp, protocol=pickle.HIGHEST_PROTOCOL)

In [112]:
last_embedding_players['Lyon']

[array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7826086956521741, 1.0],
       dtype=object),
 array([0.0, 0.0, 0.0, 0.0, 0.27272727272727304, 0.0, 0.14285714285714302,
        0.0, 0.7826086956521741, 1.0], dtype=object),
 array([0.03225806451612903, 0.06912442396313392, 0.04032258064516129,
        0.06451612903225803, 0.12609970674486815, 0.1174193548387097,
        0.0967741935483872, 0.018433179723502325, 0.7158485273492291, 1.0],
       dtype=object),
 array([0.0, 0.035714285714286004, 0.125, 0.0, 0.18181818181818202, 0.0,
        0.14285714285714302, 0.0, 0.39130434782608703, 1.0], dtype=object),
 array([0.04411764705882353, 0.09663865546218509, 0.08823529411764706,
        0.019607843137254884, 0.03208556149732624, 0.07294117647058823,
        0.11764705882352947, 0.04201680672268912, 0.43580562659846545, 1.0],
       dtype=object),
 array([0.0, 0.0, 0.0, 0.0, 0.13636363636363652, 0.04, 0.285714285714286,
        0.0, 0.7826086956521741, 1.0], dtype=object),
 array([0.0, 0.0,

In [113]:
def get_teamwise_list(team_name,home_flag):
    teamwise_list = []
    for elem in last_embedding_players[team_name]:
        elem2 = np.append(elem[:-1],home_flag)
        teamwise_list.append(elem2)
    
    return np.asarray(teamwise_list)
    

In [114]:
match_1 = []
match_1.append(get_teamwise_list('Juventus',1))
match_1.append(get_teamwise_list('Lyon',0))

match_1_npy = np.asarray(match_1)
match_1_npy.shape
with open('Juventus_Lyon_players.npy', 'wb') as f:
    np.save(f, match_1_npy)

In [115]:
match_2 = []
match_2.append(get_teamwise_list('Man. City',1))
match_2.append(get_teamwise_list('Real Madrid',0))

match_2_npy = np.asarray(match_2)
match_2_npy.shape
with open('City_Madrid_players.npy', 'wb') as f:
    np.save(f, match_2_npy)

In [116]:
match_3 = []
match_3.append(get_teamwise_list('Bayern',1))
match_3.append(get_teamwise_list('Chelsea',0))

match_3_npy = np.asarray(match_3)
match_3_npy.shape
with open('Bayern_Chelsea_players.npy', 'wb') as f:
    np.save(f, match_3_npy)

In [117]:
match_4 = []
match_4.append(get_teamwise_list('Barcelona',1))
match_4.append(get_teamwise_list('Napoli',0))

match_4_npy = np.asarray(match_4)
match_4_npy.shape
with open('Barca_Napoli_players.npy', 'wb') as f:
    np.save(f, match_4_npy)